/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;
import BLL.ThanhVienBLL;
import BLL.ThietBiBLL;
import hibernate.entity.thanhvien;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 *
 * @author ACER
 */
public class QuanLyThanhVienFormEdit extends javax.swing.JDialog {

    QuanLyThanhVienForm form;
    private int matv;
    private ThanhVienBLL tvBll;
    public QuanLyThanhVienFormEdit(QuanLyThanhVienForm f,int maTV) {
        initComponents();
        form=f;
        matv=maTV;
        tvBll=new ThanhVienBLL();
        LoadThongTin(matv);
    }
    protected void LoadThongTin(int matv){
        thanhvien obj =tvBll.getById(matv);
        txbTen.setText(obj.getHoTen());
        txbKhoa.setText(obj.getKhoa());
        txbNganh.setText(obj.getNganh());
        String sdt=String.valueOf(obj.getSDT());
        while(!sdt.matches("\\d{10}")){sdt="0"+sdt;}
        txbSdt.setText(sdt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        txbTen = new javax.swing.JTextField();
        txbKhoa = new javax.swing.JTextField();
        txbNganh = new javax.swing.JTextField();
        txbSdt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txbTen.setText(" ");

        txbKhoa.setText(" ");

        txbNganh.setText(" ");

        txbSdt.setText(" ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("SỬA THÀNH VIÊN");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("SỬA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tên Khoa:");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("THOÁT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tên thành viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tên ngành: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Số điện thoại: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jButton2)))
                                .addContainerGap(36, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txbTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(CheckValid()){
            thanhvien obj =tvBll.getById(matv);
            obj.setHoTen(txbTen.getText());
            obj.setKhoa(txbKhoa.getText());
            obj.setSDT(Integer.parseInt(txbSdt.getText()));
            if(obj.getNganh().equals(txbNganh.getText())) {
                if(tvBll.EditThanhVien(obj)==1){
                    JOptionPane.showMessageDialog(null,"Sửa thông tin thành công","Message",JOptionPane.INFORMATION_MESSAGE);
                    form.LoadThanhVien(null);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Sửa không thành công","Message",JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                int nganh=Integer.parseInt(maNganh());
                int dau=matv/1000000*100;
                int maTV=nganh+dau;
                obj.setMaTV(checkTrung(maTV));
                obj.setNganh(txbNganh.getText());
                thanhvien objDelete= tvBll.getById(matv);

                if(tvBll.RemoveThanhVien(objDelete)==1 && tvBll.AddThanhVien(obj)==1){
                    JOptionPane.showMessageDialog(null,"Sửa thông tin thành công","Message",JOptionPane.INFORMATION_MESSAGE);
                    form.LoadThanhVien(null);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Sửa không thành công","Message",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    private boolean CheckValid(){
        if(txbTen.getText().isBlank() || txbKhoa.getText().isBlank()||txbNganh.getText().isBlank()||txbSdt.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Không được để trống thongo tin!","Message",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(!txbTen.getText().matches(".*\\d.*")){}
        else{
            JOptionPane.showMessageDialog(null,"Tên không được chứa số!","Message",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(!txbSdt.getText().matches("\\d{10}")){
            JOptionPane.showMessageDialog(null,"Số điện thoại phải đủ 10 số","Message",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    private int checkTrung(int matv){
        matv*=10000;
        while(tvBll.CheckMaTTExists(matv) > 0){
            int ma=matv/10000*10000;
            Random rand=new Random();
            int randomNumber = rand.nextInt(9000) + 1000;
            matv=ma+randomNumber;
        }
        return matv;
    }
    private String maNganh(){
        String maKhoa = "";
        String nganh = txbNganh.getText();

        List<String> daChon = new ArrayList<>();

        if (nganh.equals("Địa")) {
            maKhoa = "11";
            daChon.add(maKhoa);
        } else if (nganh.equals("Sử")) {
            maKhoa = "10";
            daChon.add(maKhoa);
        } else if (nganh.equals("Văn")) {
            maKhoa = "09";
            daChon.add(maKhoa);
        } else if (nganh.equals("Anh")) {
            maKhoa = "13";
            daChon.add(maKhoa);
        } else if (nganh.equals("NNA")) {
            maKhoa = "38";
            daChon.add(maKhoa);
        } else if (nganh.equals("Toán")) {
            maKhoa = "48";
            daChon.add(maKhoa);
        } else if (nganh.equals("LTH")) {
            maKhoa = "53";
            daChon.add(maKhoa);
        } else if (nganh.equals("QTKD")) {
            maKhoa = "55";
            daChon.add(maKhoa);
        } else if (nganh.equals("Lí")) {
            maKhoa = "02";
            daChon.add(maKhoa);
        } else if (nganh.equals("CNTT")) {
            maKhoa = "41";
            daChon.add(maKhoa);
        } else if (nganh.equals("HTTT")) {
            maKhoa = "48";
            daChon.add(maKhoa);
        } else {
            // Tạo số ngẫu nhiên không trùng lặp
            Random rand = new Random();
            boolean trungLap = true;
            while (trungLap) {
                int randomNumber = rand.nextInt(90) + 10; // Số ngẫu nhiên từ 10 đến 99
                if (!daChon.contains(String.valueOf(randomNumber))) {
                    maKhoa = String.valueOf(randomNumber);
                    trungLap = false;
                }
            }
        }
        return maKhoa;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }



    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txbKhoa;
    private javax.swing.JTextField txbNganh;
    private javax.swing.JTextField txbSdt;
    private javax.swing.JTextField txbTen;
    // End of variables declaration
}
