/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BLL.ThanhVienBLL;
import BLL.XuLyBLL;
import hibernate.entity.thanhvien;
import hibernate.entity.xuly;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author USER
 */
public class XuLyViPhamFormAdd extends javax.swing.JFrame {

     XuLyViPhamForm form;
    private XuLyBLL xlBll;
    private ThanhVienBLL tvBll;
    public XuLyViPhamFormAdd(XuLyViPhamForm f) {
       initComponents();
        form = f;
        xlBll = new XuLyBLL();
        tvBll = new ThanhVienBLL();
        LoadThongTinThanhVien();
    }
    private void LoadThongTinThanhVien() {
        List<String> thanhvienList = tvBll.GetAllThanhVien1();

        if (thanhvienList == null || thanhvienList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu thành viên", "Message", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (String tv : thanhvienList) {
            cbThanhVien.addItem(tv);
        }
    }

     public void AddXuLy() {
        if (checkValid()) {
            String soTienText = txtSoTien.getText();
            int soTien = Integer.parseInt(soTienText);
            String selectedValue = (String) cbThanhVien.getSelectedItem();
            String[] parts = selectedValue.split("_");
            int maxl = Integer.parseInt(parts[0]);
            String hinhThucXL = String.valueOf(cbHinhThucXL.getSelectedItem());
            Date ngayXL = dateXL.getDate();
            int trangThai = 1;
            int maXL= xlBll.AuToID()+1;
            xuly xl = new xuly();
            xl.setMaXL(maXL);
            xl.setSoTien(soTien);
            xl.setMaTV(maxl);
            xl.setHinhThucXL(hinhThucXL);
            xl.setNgayXL(ngayXL);
            xl.setTrangThaiXL(trangThai);
            
            if (xlBll.AddXuLy(xl) == 1) {
                JOptionPane.showMessageDialog(null, "Thêm thành công", "Message", JOptionPane.INFORMATION_MESSAGE);
                form.loadXuLy(null);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    private boolean checkValid() {
        dateXL.getDateEditor().getUiComponent().requestFocus();
        Date selectedDate = dateXL.getDate();
        if (selectedDate != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormat.format(selectedDate);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Kiểm tra hình thức xử lý và số tiền (nếu cần)
        String hinhThucXL = String.valueOf(cbHinhThucXL.getSelectedItem());
        if (hinhThucXL.equals("Bồi thường") || hinhThucXL.equals("Khóa thẻ 1 tháng và bồi thường")) {
            String soTienText = txtSoTien.getText();
            if (!soTienText.isBlank() && !soTienText.isEmpty() && !soTienText.equals("0")) {
                try {
                    int soTien = Integer.parseInt(soTienText);
                    if (soTien > 0) {
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Số tiền phải là số nguyên dương", "Message", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Số tiền phải là số nguyên", "Message", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Số tiền không được để trống", "Message", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            txtSoTien.setText("0");
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        cbThanhVien = new javax.swing.JComboBox<>();
        cbHinhThucXL = new javax.swing.JComboBox<>();
        txtSoTien = new javax.swing.JTextField();
        dateXL = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm xử lý vi phạm");

        jLabel2.setText("Thành viên: ");

        jLabel3.setText("Hình thức  xử lý:");

        jLabel4.setText("Số tiền:");

        jLabel5.setText("Ngày xử lý:");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        cbHinhThucXL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bồi thường", "Khóa thẻ 1 tháng và bồi thường", "Khóa thẻ 1 tháng", "Khóa thẻ 2 tháng", " " }));
        cbHinhThucXL.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                if (evt.getStateChange() == ItemEvent.SELECTED) {
                    if (cbHinhThucXL.getSelectedItem().equals("Bồi thường") || cbHinhThucXL.getSelectedItem().equals("Khóa thẻ 1 tháng và bồi thường")) {
                        txtSoTien.setEnabled(true);
                    } else {
                        txtSoTien.setEnabled(false);
                    }
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHinhThucXL, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateXL, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbHinhThucXL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateXL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        AddXuLy();
    }//GEN-LAST:event_btnAddMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cbHinhThucXL;
    private javax.swing.JComboBox<String> cbThanhVien;
    private com.toedter.calendar.JDateChooser dateXL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtSoTien;
    // End of variables declaration//GEN-END:variables
}
